namespace DG.Tweening
{
    public class DOTweenCroppingHelper : UnityEngine.MonoBehaviour
    {
        public void Start()
        {
            _ = typeof(DG.Tweening.AutoPlay);
            _ = typeof(DG.Tweening.AxisConstraint);
            _ = typeof(DG.Tweening.Color2);
            _ = typeof(DG.Tweening.Core.ABSSequentiable);
            _ = typeof(DG.Tweening.Core.Debugger);
            _ = typeof(DG.Tweening.Core.DOGetter<>);
            _ = typeof(DG.Tweening.Core.DOSetter<>);
            _ = typeof(DG.Tweening.Core.DOTweenComponent);
            _ = typeof(DG.Tweening.Core.DOTweenExternalCommand);
            _ = typeof(DG.Tweening.Core.DOTweenSettings);
            _ = typeof(DG.Tweening.Core.DOTweenSettings.ModulesSetup);
            _ = typeof(DG.Tweening.Core.DOTweenSettings.SafeModeOptions);
            _ = typeof(DG.Tweening.Core.DOTweenSettings.SettingsLocation);
            _ = typeof(DG.Tweening.Core.DOTweenUtils);
            _ = typeof(DG.Tweening.Core.Easing.Bounce);
            _ = typeof(DG.Tweening.Core.Easing.EaseCurve);
            _ = typeof(DG.Tweening.Core.Easing.EaseManager);
            _ = typeof(DG.Tweening.Core.Easing.Flash);
            _ = typeof(DG.Tweening.Core.Enums.NestedTweenFailureBehaviour);
            _ = typeof(DG.Tweening.Core.Enums.RewindCallbackMode);
            _ = typeof(DG.Tweening.Core.Enums.SafeModeLogBehaviour);
            _ = typeof(DG.Tweening.Core.Enums.SpecialStartupMode);
            _ = typeof(DG.Tweening.Core.Enums.UpdateNotice);
            _ = typeof(DG.Tweening.Core.Extensions);
            _ = typeof(DG.Tweening.Core.TweenerCore<,,>);
            _ = typeof(DG.Tweening.CustomPlugins.PureQuaternionPlugin);
            _ = typeof(DG.Tweening.DOCurve);
            _ = typeof(DG.Tweening.DOCurve.CubicBezier);
            _ = typeof(DG.Tweening.DOTween);
            _ = typeof(DG.Tweening.DOVirtual);
            _ = typeof(DG.Tweening.Ease);
            _ = typeof(DG.Tweening.EaseFactory);
            _ = typeof(DG.Tweening.EaseFunction);
            _ = typeof(DG.Tweening.IDOTweenInit);
            _ = typeof(DG.Tweening.LinkBehaviour);
            _ = typeof(DG.Tweening.LogBehaviour);
            _ = typeof(DG.Tweening.LoopType);
            _ = typeof(DG.Tweening.PathMode);
            _ = typeof(DG.Tweening.PathType);
            _ = typeof(DG.Tweening.Plugins.CircleOptions);
            _ = typeof(DG.Tweening.Plugins.CirclePlugin);
            _ = typeof(DG.Tweening.Plugins.ColorPlugin);
            _ = typeof(DG.Tweening.Plugins.Core.ABSTweenPlugin<,,>);
            _ = typeof(DG.Tweening.Plugins.Core.IPlugSetter<,,,>);
            _ = typeof(DG.Tweening.Plugins.Core.ITPlugin<,,,>);
            _ = typeof(DG.Tweening.Plugins.Core.ITweenPlugin);
            _ = typeof(DG.Tweening.Plugins.Core.PathCore.ControlPoint);
            _ = typeof(DG.Tweening.Plugins.Core.PathCore.Path);
            _ = typeof(DG.Tweening.Plugins.DoublePlugin);
            _ = typeof(DG.Tweening.Plugins.FloatPlugin);
            _ = typeof(DG.Tweening.Plugins.IntPlugin);
            _ = typeof(DG.Tweening.Plugins.LongPlugin);
            _ = typeof(DG.Tweening.Plugins.Options.ColorOptions);
            _ = typeof(DG.Tweening.Plugins.Options.FloatOptions);
            _ = typeof(DG.Tweening.Plugins.Options.IPlugOptions);
            _ = typeof(DG.Tweening.Plugins.Options.NoOptions);
            _ = typeof(DG.Tweening.Plugins.Options.OrientType);
            _ = typeof(DG.Tweening.Plugins.Options.PathOptions);
            _ = typeof(DG.Tweening.Plugins.Options.QuaternionOptions);
            _ = typeof(DG.Tweening.Plugins.Options.RectOptions);
            _ = typeof(DG.Tweening.Plugins.Options.StringOptions);
            _ = typeof(DG.Tweening.Plugins.Options.UintOptions);
            _ = typeof(DG.Tweening.Plugins.Options.Vector3ArrayOptions);
            _ = typeof(DG.Tweening.Plugins.Options.VectorOptions);
            _ = typeof(DG.Tweening.Plugins.PathPlugin);
            _ = typeof(DG.Tweening.Plugins.QuaternionPlugin);
            _ = typeof(DG.Tweening.Plugins.RectOffsetPlugin);
            _ = typeof(DG.Tweening.Plugins.RectPlugin);
            _ = typeof(DG.Tweening.Plugins.StringPlugin);
            _ = typeof(DG.Tweening.Plugins.UintPlugin);
            _ = typeof(DG.Tweening.Plugins.UlongPlugin);
            _ = typeof(DG.Tweening.Plugins.Vector2Plugin);
            _ = typeof(DG.Tweening.Plugins.Vector3ArrayPlugin);
            _ = typeof(DG.Tweening.Plugins.Vector3Plugin);
            _ = typeof(DG.Tweening.Plugins.Vector4Plugin);
            _ = typeof(DG.Tweening.RotateMode);
            _ = typeof(DG.Tweening.ScrambleMode);
            _ = typeof(DG.Tweening.Sequence);
            _ = typeof(DG.Tweening.ShakeRandomnessMode);
            _ = typeof(DG.Tweening.ShortcutExtensions);
            _ = typeof(DG.Tweening.Tween);
            _ = typeof(DG.Tweening.TweenCallback);
            _ = typeof(DG.Tweening.TweenCallback<>);
            _ = typeof(DG.Tweening.Tweener);
            _ = typeof(DG.Tweening.TweenExtensions);
            _ = typeof(DG.Tweening.TweenParams);
            _ = typeof(DG.Tweening.TweenSettingsExtensions);
            _ = typeof(DG.Tweening.TweenType);
            _ = typeof(DG.Tweening.UpdateType);
        }
    }
}